# Generated by Django 2.0.13 on 2019-07-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=60)),
                ('comentario', models.CharField(max_length=250)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop.Producto')),
            ],
        ),
    ]
