# Generated by Django 2.1.2 on 2019-06-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop', '0002_auto_20190628_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(default='img_productos/noimage.jpeg', upload_to='img_productos/'),
        ),
    ]
